
services:
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:80"
  #   restart: always

  authservice:
    build: ./backend/Auth_service
    ports:
      - "8083:8081"
    restart: always
  
  db_service:
    build: ./backend/db_service
    ports:
      - "8082:8081"
    networks:
      - default

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: TestPassword
      POSTGRES_DB: testdb
    ports:
      - "5439:5432"
    networks:
      - default
    restart: always

networks:
  default:
    driver: bridge
