spring.application.name=db_service
server.port=8081
# Database configuration
spring.datasource.url=jdbc:postgresql://postgres:5432/testdb
#spring.datasource.url=jdbc:postgresql://localhost:5432/testdb
spring.datasource.username=testuser
spring.datasource.password=TestPassword
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=always
spring.sql.init.platform=postgres
spring.jpa.defer-datasource-initialization=true
server.address=0.0.0.0
server.forward-headers-strategy=NONE
server.tomcat.remoteip.host-header=x-forwarded-host 